baseURL: https://roudranil.github.io/
languageCode: en-us
theme: PaperMod

enableEmoji: true
enableGitInfo: true

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  assets:
    disableFingerprinting: true
    favicon: favicon/favicon.ico
    favicon16x16: favicon/favicon-16x16.png
    favicon32x32: favicon/favicon-32x32.png
    apple_touch_icon: favicon/apple_touch_icon.png
    safari_pinned_tab: favicon/safari_pinned_tab.png
     
  profileMode:
    enabled: true
    title: "Hello there \U0001F44B"
    subtitle: |
      <br>I am Roudranil and I am a masters student in Data Science.<br><br>
      
      I am primarily interest in all sorts of practical applications of AI and machine learning. I have a keen interest in the applications of ML in the audio and music domain. Feel free to look at [`About`](/about/) to know more about me or [`Projects`](/projects/) to view my work. <br><br>

    imageUrl: img/profilephoto.png
    # imageTitle: <title of image as alt>
    imageWidth: 200
    imageHeight: 200

  AuthorName: Roudranil Das
  GitHubUser: roudranil
  showMenuItems: 5
  showLanguageSelector: false
  fullWidthTheme: True
  centerTheme: true
  autoCover: true
  showLastUpdated: false

  socialIcons:
    - name: email
      url: mailto:roudranil@cmi.ac.in
    - name: kaggle
      url: https://www.kaggle.com/roudranildas
    - name: linkedin
      url: https://www.linkedin.com/in/roudranil-das/
    - name: github
      url: https://github.com/Roudranil

  defaultTheme: dark

  ShowPostNavLinks: false
  ShowCodeCopyButtons: true
  ShowShareButtons: false
  ShowReadingTime: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [title, permalink, summary, content]

  math: true

languages:
  en:
    languageName: English
    title: Roudranil
    subtitle: MSc. Data Science @ CMI
    # owner: ''
    # keywords: ''
    copyright: © 2022 Roudranil Das | 
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts
    newerPosts: Newer posts
    olderPosts: Older posts
    missingContentMessage: Page not found...
    missingBackButtonLabel: Back to home page
    params:
      logo:
        logoText: roudranilD
        logoHomeLink: /
    menu:
      main:
        - identifier: about
          name: About
          url: about/
          weight: 10
        # - identifier: posts
        #   name: Posts
        #   url: /posts
        #   weight: 20
        - identifier: projects
          name: Projects
          url: /projects
          weight: 30
        - identifier: academic
          name: Academics
          url: /academics
          weight: 40
        - identifier: contact
          name: Contact
          url: contact/
          weight: 50
        - identifier: search
          name: Search
          url: search/
          weight: 60
