---
title: "PBSR"
author: "Roudranil Das"
output: html_document
---

### CW 10/08/22

```{r}
roll_no = 1:10
sample(roll_no, size = 5)

sample(roll_no, size = 5, replace = TRUE)
```

-----------------------

```{r}
attach(mtcars)
```

Lets assume for a sec that this dataset contains all the cars in the population. To get the properties of this dataset, use
```{r}
str(mtcars)
```
To get values of one column, say mpg, use
```{r}
mtcars$mpg
```

Defining this as a matrix
```{r}
mtcars_matrix <- as.matrix(mtcars)
str(mtcars_matrix)
```
Then, mtcars_matrix$mpg will throw an error.
```{r, error=T}
mtcars_matrix$mpg
```
```{r}
mean(mtcars$mpg)
```

We take a random sample of these 32 obs and calculate their mean.
```{r}
id = 1:32
set.seed(93474)
sampled_id = sample(id, size = 5, replace = T) # for the time being take with replacement
sampled_id
```
```{r}
sample_mtcars = mtcars[sampled_id,]
sample_mtcars
```

```{r}
mean(sample_mtcars$mpg)
```
So this is our sample mean.

---------------------

### CW 17/08/2022

# Randomisation

To understand the concept of randomization, note the issue in clinical trials again. We need randomised assignment of participants in the two groups. Check the R markdown file.

```{r}
attach(mtcars)
group = c("EV1", "EV2")
n = nrow(mtcars)
```

We will draw a sample at random and toss a coin. If H comes we assign it to EV1 or else we assign it to EV2.

```{r}
d1 <- d2 <- mtcars[1,]
View(d1)
d1[1,] <- d2[1,] <- NA #this sort of creates a placeholder, later it will be updated when we add more samples

coin <- c("H", "T")
set.seed(863)

for(i in 1:n){
    toss <- sample(coin, size = 1, replace = F)
    if(toss == "H"){
        d1 <- rbind.data.frame(d1, mtcars[i,])
    }else{
        d2 <- rbind.data.frame(d2, mtcars[i,])
    }
}

d1 <- d1[-1,]
d2 <- d2[-1,]
```

```{r}
EV1 <- apply(d1, 2, mean, na.rm = T)
EV2 <- apply(d2, 2, mean, na.rm = T)
avg <- cbind(EV1, EV2)
avg

EV1_sd <- apply(d1, 2, sd, na.rm = T)
EV2_sd <- apply(d2, 2, sd, na.rm = T)
sd <- cbind(EV1_sd, EV2_sd)
sd
```



